# Generated by Django 3.2.5 on 2021-10-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateTour',
        ),
    ]
