# Generated by Django 3.2.5 on 2021-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='photos',
            field=models.ImageField(default=None, upload_to='static/upload/tours/%Y/%m'),
        ),
    ]
