# Generated by Django 3.2.5 on 2021-09-17 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_auto_20210917_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tours.tours'),
        ),
        migrations.AlterField(
            model_name='ratetour',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
