# Generated by Django 3.2.5 on 2021-08-02 10:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_tours_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, upload_to='upload/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', related_query_name='my_category', to='Tours.category'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tours',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='photos',
            field=models.ImageField(default=None, upload_to='tours/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='tours',
            unique_together={('name',)},
        ),
    ]
