# Generated by Django 3.2.5 on 2021-08-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_auto_20210802_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tours',
            name='tags',
            field=models.ManyToManyField(related_name='tags', related_query_name='my_tags', to='Tours.Tag'),
        ),
    ]
