# Generated by Django 3.2.5 on 2021-09-19 07:45

import Tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_auto_20210917_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], default=Tours.models.Gender['MALE'], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUSINESS', 'Nhân viên kinh doanh'), ('SALESMAN', 'Nhân viên bán hàng'), ('EMPLOYEE_MANAGER', 'Quản lý nhân sự'), ('MANAGER', 'Quản lý'), ('USER', 'Khách hàng')], default=Tours.models.Role['USER'], max_length=20),
        ),
        migrations.AlterField(
            model_name='tours',
            name='vehicle',
            field=models.CharField(choices=[('OTO', 'Ô tô'), ('YACHT', 'Du thuyền'), ('PLANE', 'Máy bay')], default=Tours.models.Vehicle['OTO'], max_length=20),
        ),
    ]
