# Generated by Django 3.2.5 on 2021-08-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/tupload/avatars/%Y/%m'),
        ),
    ]
