# Generated by Django 3.2.5 on 2021-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_ratetour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetour',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetour',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
