# Generated by Django 3.2.5 on 2021-08-20 10:21

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_auto_20210804_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], default='Nam', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('USER', 'User')], default='User', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='Active', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_user_tourbooking', related_query_name='my_user_tourbooking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('method', models.CharField(choices=[('ZALOPAY', 'ZaloPay'), ('MOMO', 'Momo'), ('CASH', 'Cash')], default='Cash', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_user_payment', related_query_name='my_user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
