# Generated by Django 3.2.5 on 2021-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_auto_20210919_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='content',
            field=models.ManyToManyField(related_name='content', related_query_name='commenttour', to='Tours.CommentTour'),
        ),
    ]
