# Generated by Django 3.2.5 on 2021-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_auto_20211011_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='tour_view',
            field=models.ManyToManyField(related_name='tour_view', to='Tours.TourView'),
        ),
    ]
