# Generated by Django 3.2.5 on 2021-09-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_tours_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='content',
        ),
    ]
