# Generated by Django 3.2.5 on 2021-08-21 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_auto_20210820_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateField(),
        ),
    ]
