# Generated by Django 3.2.5 on 2021-10-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_tours_tour_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='tour_view',
        ),
    ]
