# Generated by Django 3.2.5 on 2021-08-21 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2021, 8, 21)),
        ),
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
