# Generated by Django 3.2.5 on 2021-12-15 09:16

import Tours.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_remove_tours_tour_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tours.tours')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='adult',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Đã thanh toán'), ('UNPAID', 'Chưa thanh toán'), ('EXPIRED', 'Đã hết hạn')], default=Tours.models.StatusPayment['UNPAID'], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUSINESS', 'Nhân viên kinh doanh'), ('SALESMAN', 'Nhân viên bán hàng'), ('USER', 'Khách hàng')], default=Tours.models.Role['USER'], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_payment', related_query_name='tour_payment', to='Tours.tours'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', related_query_name='user_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TourBooking',
        ),
        migrations.AddField(
            model_name='payment',
            name='datedetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datedetail_payment', related_query_name='datedetail_payment', to='Tours.datedetail'),
        ),
    ]
