# Generated by Django 3.2.5 on 2021-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_remove_tours_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttour',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='tours',
            name='comment',
            field=models.ManyToManyField(related_name='comment', related_query_name='commenttour', to='Tours.CommentTour'),
        ),
    ]
