# Generated by Django 3.2.5 on 2021-12-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0007_auto_20211215_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='datedetail',
        ),
        migrations.DeleteModel(
            name='DateDetail',
        ),
    ]
