# Generated by Django 3.2.5 on 2021-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0007_auto_20210821_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateField(),
        ),
    ]
