# Generated by Django 3.2.5 on 2021-08-22 09:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_alter_tours_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_payment', related_query_name='tour_payment', to='Tours.tours'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourbooking_payment', related_query_name='tourbooking_payment', to='Tours.tours'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2021, 8, 22)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payment', related_query_name='user_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tourbooking', related_query_name='user_tourbooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tours',
            name='photos',
            field=models.ImageField(default=None, upload_to='upload/tours/%Y/%m'),
        ),
        migrations.CreateModel(
            name='RateTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=20)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_payment', related_query_name='rate_payment', to='Tours.tours')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_user_ratetour', related_query_name='my_user_ratetour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('photo', models.FileField(null=True, upload_to='upload/comment/%Y/%m')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_payment', related_query_name='comment_payment', to='Tours.tours')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_user_commenttour', related_query_name='my_user_commenttour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
