# Generated by Django 3.2.5 on 2021-08-22 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0009_auto_20210822_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 13, 19, 48, 543689, tzinfo=utc)),
        ),
    ]
