# Generated by Django 3.2.5 on 2021-12-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0010_auto_20211220_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_detail', related_query_name='my_price_detail', to='Tours.pricedetail'),
        ),
    ]
