# Generated by Django 3.2.5 on 2021-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0011_alter_tours_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='price',
        ),
        migrations.AddField(
            model_name='tours',
            name='price_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='price_children',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PriceDetail',
        ),
    ]
