# Generated by Django 3.2.5 on 2021-12-21 14:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0012_auto_20211221_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentblog',
            name='user',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rateblog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rateblog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tours.blog'),
        ),
        migrations.AlterField(
            model_name='rateblog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tours.blog'),
        ),
        migrations.AlterField(
            model_name='rateblog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rateblog',
            unique_together={('blog', 'user')},
        ),
    ]
