# Generated by Django 3.2.5 on 2021-12-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0013_auto_20211221_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
