# Generated by Django 3.2.5 on 2021-12-22 09:40

import Tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0015_alter_payment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ZALOPAY', 'ZaloPay'), ('MOMO', 'Momo'), ('TRANSFER', 'Chuyển khoản')], default=Tours.models.Methods['TRANSFER'], max_length=20, null=True),
        ),
    ]
