# Generated by Django 3.2.5 on 2021-12-22 09:42

import Tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0016_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Đã thanh toán'), ('UNPAID', 'Chưa thanh toán'), ('EXPIRED', 'Đã hết hạn')], default=Tours.models.StatusPayment['UNPAID'], max_length=20, null=True),
        ),
    ]
