# Generated by Django 3.2.5 on 2021-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0017_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Đã thanh toán'), ('UNPAID', 'Chưa thanh toán'), ('EXPIRED', 'Đã hết hạn')], default='Chưa thanh toán', max_length=20, null=True),
        ),
    ]
