# Generated by Django 3.2.5 on 2021-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0018_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ZALOPAY', 'ZaloPay'), ('MOMO', 'Momo'), ('TRANSFER', 'Chuyển khoản')], default='Chuyển khoản', max_length=20, null=True),
        ),
    ]
